version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd server   # 위치 확인
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./server/build/libs/*.jar)
artifacts:
  files:
    - server/build/libs/*.jar   #경로지정 확인
    - server/scripts/**
    - server/appspec.yml
  discard-paths: yes